# Generated by Django 3.2.18 on 2023-04-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_link', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mindmaps', to='revision_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='revision_app.mindmap')),
            ],
            options={
                'ordering': ['mindmap__category__title', 'mindmap__title'],
            },
        ),
        migrations.CreateModel(
            name='RevisionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revision_done', models.BooleanField(default=False)),
                ('revision_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_item', to='revision_app.revisiongroup')),
            ],
        ),
        migrations.AddField(
            model_name='revisiongroup',
            name='revision_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='revision_app.revisionlevel'),
        ),
    ]
