# Generated by Django 3.2.18 on 2023-04-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiongroup',
            name='revision_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='revision_app.revisionlevel'),
        ),
    ]
