# Generated by Django 3.2.18 on 2023-04-10 06:35

from django.db import migrations, models
import revision_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0002_alter_revisiongroup_revision_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=revision_app.models.get_default_my_date),
        ),
    ]
